// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1VqMe-dn2pmUAoywccTdaq33tMib42Nc',
    appId: '1:803308160980:web:965a8b365429c5a1eab841',
    messagingSenderId: '803308160980',
    projectId: 'movie-app-d18aa',
    authDomain: 'movie-app-d18aa.firebaseapp.com',
    storageBucket: 'movie-app-d18aa.appspot.com',
    measurementId: 'G-JTZJVY7JKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmHhEkgJcD4p0lqDnBX0QgvcyG-IV5W_E',
    appId: '1:803308160980:android:c6addabc5718924deab841',
    messagingSenderId: '803308160980',
    projectId: 'movie-app-d18aa',
    storageBucket: 'movie-app-d18aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qNfXmLzRVtaEnt3ERApS9OyoiOM9c48',
    appId: '1:803308160980:ios:154483b448052030eab841',
    messagingSenderId: '803308160980',
    projectId: 'movie-app-d18aa',
    storageBucket: 'movie-app-d18aa.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qNfXmLzRVtaEnt3ERApS9OyoiOM9c48',
    appId: '1:803308160980:ios:04d683cddd4cf6eeeab841',
    messagingSenderId: '803308160980',
    projectId: 'movie-app-d18aa',
    storageBucket: 'movie-app-d18aa.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
